## Installation

```python
!pip3 install numpy
```

In [1]:
!pip3 install numpy

     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.9 kB 262.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.9 kB 375.8 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 405.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/16.3 MB ? eta -:--:--
   ---------------------------------------- 0.1/16.3 MB 3.6 MB/s eta 0:00:05
   - -------------------------------------- 0.7/16.3 MB 8.5 MB/s eta 0:00:02
   -- ------------------------------------- 1.2/16.3 MB 9.7 MB/s eta 0:00:02
   ---- ----------------------------------- 1.8/16.3 MB 10.1 MB/s eta 0:00:02
   ----- ---------------------------------- 2.3/16.3 MB 10.4 MB/s eta 0:00:02
   ------ --------------------------------- 2.6/16.3 MB 9.9 MB/s eta 0:00:02
   ------- -------------------------------- 2.9/16.3 MB 9.7 MB/s eta 0:00:02
   -


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

# 1. Create

In [7]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((3,3,3))

In [8]:
data

array([[[0.34991853, 0.66550044, 0.2801731 , 0.59164739],
        [0.18838693, 0.83829825, 0.5885628 , 0.87707008],
        [0.20283374, 0.27127056, 0.61442986, 0.13118093]],

       [[0.86224827, 0.31153162, 0.28548117, 0.33595466],
        [0.73440516, 0.15279692, 0.41612262, 0.12863924],
        [0.14652537, 0.14784419, 0.46449173, 0.21655896]]])

In [9]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [10]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [11]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [12]:
type(arr)

numpy.ndarray

# 2. Read

In [13]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [14]:
types

dtype('float64')

In [15]:
# Slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [16]:
singleval

np.float64(0.34991853261998895)

In [17]:
data

array([[[0.34991853, 0.66550044, 0.2801731 , 0.59164739],
        [0.18838693, 0.83829825, 0.5885628 , 0.87707008],
        [0.20283374, 0.27127056, 0.61442986, 0.13118093]],

       [[0.86224827, 0.31153162, 0.28548117, 0.33595466],
        [0.73440516, 0.15279692, 0.41612262, 0.12863924],
        [0.14652537, 0.14784419, 0.46449173, 0.21655896]]])

# 3. Update

In [18]:
list1 = np.random.rand(10) 
list2 = np.random.rand(10) 

In [19]:
list2

array([0.31074646, 0.99764208, 0.18804286, 0.47545809, 0.05974404,
       0.86312743, 0.63072534, 0.43623609, 0.27685815, 0.69012082])

In [20]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
# these four are element wise

dot = np.dot(list1, list2)

In [21]:
dot

np.float64(2.4360199710684816)

In [28]:
# Stat Functions
sqrt = np.sqrt(49)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [29]:
sqrt

np.float64(7.0)

In [23]:
maxs

np.float64(0.9622444528669721)

In [24]:
data

array([[[0.34991853, 0.66550044, 0.2801731 , 0.59164739],
        [0.18838693, 0.83829825, 0.5885628 , 0.87707008],
        [0.20283374, 0.27127056, 0.61442986, 0.13118093]],

       [[0.86224827, 0.31153162, 0.28548117, 0.33595466],
        [0.73440516, 0.15279692, 0.41612262, 0.12863924],
        [0.14652537, 0.14784419, 0.46449173, 0.21655896]]])

In [25]:
data[0][0][0] = 700

In [21]:
data

array([[[7.00000000e+02, 3.69082338e-01, 9.00527525e-01, 1.07024332e-01],
        [5.59167732e-01, 2.90804549e-01, 1.80171286e-02, 7.97232649e-01],
        [3.19069766e-01, 9.40366141e-02, 9.49223261e-01, 1.14804725e-01]],

       [[4.13763474e-01, 3.14099983e-01, 2.72447436e-01, 7.68408114e-01],
        [2.93284177e-01, 9.37086775e-01, 6.24786554e-01, 3.84317906e-01],
        [2.00317361e-02, 3.66648784e-01, 8.45020869e-01, 1.95664272e-01]]])

In [22]:
data.sort()
data

array([[[1.07024332e-01, 3.69082338e-01, 9.00527525e-01, 7.00000000e+02],
        [1.80171286e-02, 2.90804549e-01, 5.59167732e-01, 7.97232649e-01],
        [9.40366141e-02, 1.14804725e-01, 3.19069766e-01, 9.49223261e-01]],

       [[2.72447436e-01, 3.14099983e-01, 4.13763474e-01, 7.68408114e-01],
        [2.93284177e-01, 3.84317906e-01, 6.24786554e-01, 9.37086775e-01],
        [2.00317361e-02, 1.95664272e-01, 3.66648784e-01, 8.45020869e-01]]])

In [23]:
print(data.shape)

(2, 3, 4)


In [24]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [25]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [26]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# 4. Delete

In [27]:
data

array([[[1.07024332e-01, 3.69082338e-01, 9.00527525e-01, 7.00000000e+02,
         1.80171286e-02, 2.90804549e-01],
        [5.59167732e-01, 7.97232649e-01, 9.40366141e-02, 1.14804725e-01,
         3.19069766e-01, 9.49223261e-01]],

       [[2.72447436e-01, 3.14099983e-01, 4.13763474e-01, 7.68408114e-01,
         2.93284177e-01, 3.84317906e-01],
        [6.24786554e-01, 9.37086775e-01, 2.00317361e-02, 1.95664272e-01,
         3.66648784e-01, 8.45020869e-01]]])

In [28]:
np.delete(data, 0, axis=1)

array([[[0.55916773, 0.79723265, 0.09403661, 0.11480473, 0.31906977,
         0.94922326]],

       [[0.62478655, 0.93708677, 0.02003174, 0.19566427, 0.36664878,
         0.84502087]]])

In [29]:
np.save("new array", data)

In [30]:
test = np.load("new array.npy")

In [31]:
test

array([[[1.07024332e-01, 3.69082338e-01, 9.00527525e-01, 7.00000000e+02,
         1.80171286e-02, 2.90804549e-01],
        [5.59167732e-01, 7.97232649e-01, 9.40366141e-02, 1.14804725e-01,
         3.19069766e-01, 9.49223261e-01]],

       [[2.72447436e-01, 3.14099983e-01, 4.13763474e-01, 7.68408114e-01,
         2.93284177e-01, 3.84317906e-01],
        [6.24786554e-01, 9.37086775e-01, 2.00317361e-02, 1.95664272e-01,
         3.66648784e-01, 8.45020869e-01]]])